#image: openjdk:8

before_script:
  - sudo apt-get update -qq && sudo apt-get install -y -qq openjdk-8-jdk-headless maven
  - mvn clean compile -DskipTests
unit-tests:
  script:
    - mvn test

build-project:
  script:
    - mvn package -DskipTests -Dverify=false